##########################################
# make time-series plots (other than the best fit plot)
# these show time-series for different doses explored by the simulation runs
# these figures are shown in the supplement
##########################################
# load packages needed by this script and function
library(ggplot2)
library(dplyr)
library(patchwork)
library(here)

source(here::here('code/plotting-code/timeseries-plot-function.R'))

# data for the time series plots is generated by the run-dose-predictions-simulations.R script.
# it is stored in the timeseries_df component of each list element
# load simulation results
dose_results <- readRDS(here::here('results','output', 'model1-dose-response-results.Rds'))

# to get data for plotting best fit figures
bestfit_list <- readRDS(here("results", "output", "model1-bestfit-single.Rds"))
#bestfit_list <- readRDS(here("results", "output", "bestfit-sample.Rds"))


# determine the dose levels for which full time-series were recorded
timeseries_doses <- attr(dose_results, "ts_doses")

format_dose_label <- function(dose) {
  if (isTRUE(all.equal(dose, 0))) {
    return("no drug")
  }
  paste0(format(dose, trim = TRUE, scientific = FALSE), " mg/kg")
}

dose_levels_labels <- vapply(timeseries_doses, format_dose_label, character(1))

# keep only the 'timeseries_df' from each element
df_list <- lapply(dose_results, `[[`, "timeseries_df")

# only make these timeseries figures for the baseline values of the fixed parameter set, not the samples
all_ts <- df_list[[1]]

schedule_files <- c(
  s1 = 'timeseries-baseline.png',
  s2 = 'timeseries-d2tx.png',
  s3 = 'timeseries-d3tx.png',
  s4 = 'timeseries-dailytx.png',
  s5 = 'timeseries-singletx.png'
)

for (schedule_id in names(schedule_files)) {
  schedule_df <- all_ts |>
    filter(Schedule == schedule_id)

  ts_plot <- plot_timeseries(
    data = NULL,
    modelfit = schedule_df,
    tmax = 7,
    dose_levels = timeseries_doses,
    dose_levels_labels = dose_levels_labels
  )

  plot(ts_plot)

  png(
    here::here('results', 'figures', schedule_files[[schedule_id]]),
    width = 8,
    height = 5,
    units = 'in',
    res = 300
  )
  plot(ts_plot)
  dev.off()
}

################################################################
# now make the best fit figures, potentially for all samples
################################################################
dose_levels_labels <- c("no drug", "10 mg/kg", "100 mg/kg")
dose_levels <- c(0, 10, 100)



nsamp = 1
# uncomment the line below to generate best fit figures for all samples of the fixed parameters
#nsamp = length(bestfit_list)
for (i in 1:nsamp) {
  bestfit <- bestfit_list[[i]]
  # get the whole dose-response object for the indicated paramter sample
  all_ts <- df_list[[i]]
  # extract the baseline scenario, which corresponds to the actual experimental setup
  all_ts <- all_ts |>
    filter(Schedule == 's1')
  # extract the dosing levels that correspond to the experimental setup
  all_ts <- all_ts |>
    filter(Dose %in% dose_levels)

  bestfit_plots <- plot_timeseries(
    data = bestfit$fitdata,
    modelfit = all_ts,
    tmax = 7,
    dose_levels,
    dose_levels_labels,
    x_jitter = 0.3
  )
  plot(bestfit_plots)
  # save plot as png file into the results folder
  figname = paste0('bestfit', i, '.png')
  png(
    here::here('results', 'figures', figname),
    width = 8,
    height = 5,
    units = 'in',
    res = 300
  )
  plot(bestfit_plots)
  dev.off()
}

