##########################################
# NLL-consistent diagnostics for saved bestfit objects
# Residuals: r_i = sqrt(w_k) * (y_i - yhat_i) / sqrt(V_i)
# V_i = sigma_add_k^2 + (sigma_prop_k * yhat_i)^2
# Includes x-axis jitter for residual plots
##########################################

library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(here)

# data for the time series plots is generated by the run-dose-predictions-simulations.R script.
# it is stored in the timeseries_df component of each list element
# load simulation results
dose_results <- readRDS(here::here('results','output', 'dose-response-results.Rds'))

# to get data for plotting best fit figures
bestfit_list <- readRDS(here("results", "output", "bestfit.Rds"))

# unpack helper objects from the dose-response results
timeseries_doses <- attr(dose_results, "ts_doses")
df_list <- lapply(dose_results, `[[`, "timeseries_df")

scenario_map <- c(
  `0` = "NoTreatment",
  `10` = "PanCytoVir10mg",
  `100` = "PanCytoVir100mg"
)
dose_levels <- as.numeric(names(scenario_map))



# ---------------- configuration ----------------
alpha_combined <- 0.85 # transparency for combined residual plot
alpha_panel <- 0.85 # transparency for faceted residual plot
alpha_gof <- 0.85 # transparency for faceted predicted vs observed
alpha_gof_all <- 0.85 # transparency for single-panel predicted vs observed
pt_size <- 2

# Jitter (in days) for residual plots
jitter_width_combined <- 0.08
jitter_width_panel <- 0.08

# Aesthetics
var_colors <- c(
  LogVirusLoad = "#0072B2", # blue
  IL6 = "#D55E00", # vermillion
  WeightLossPerc = "#009E73" # bluish-green
)
var_labs <- c(
  LogVirusLoad = "Log Virus Load",
  IL6 = "IL-6",
  WeightLossPerc = "Weight Loss (%)"
)
scen_labs <- c(
  NoTreatment = "No Treatment",
  PanCytoVir10mg = "10 mg/kg",
  PanCytoVir100mg = "100 mg/kg"
)

# ---------------- helpers (lean) ----------------
collect_params <- function(bf) {
  c(bf$fitpars, bf$fixedpars)
}

# Build a wide sigma table and ensure 'add' and 'prop' columns exist
gather_sigmas_tbl <- function(bestfit) {
  vec <- collect_params(bestfit)
  vec <- vec[!is.na(names(vec))]
  out <- tibble(name = names(vec), value = as.numeric(vec)) |>
    dplyr::filter(grepl("^sigma_(add|prop)_", name)) |>
    tidyr::extract(
      name,
      into = c("type", "Quantity"),
      regex = "^sigma_(add|prop)_(.+)$"
    ) |>
    dplyr::select(Quantity, type, value) |>
    tidyr::pivot_wider(names_from = type, values_from = value)
  if (!"add" %in% names(out)) {
    out$add <- 0
  }
  if (!"prop" %in% names(out)) {
    out$prop <- 0
  }
  out
}

# Faceted residual plot with per-panel symmetric y-lims (via blanks) + x-jitter
build_panel_plot <- function(df, ycol, alpha_pt, shape_vals, jitter_width) {
  pad_df <- df %>%
    group_by(Quantity) %>%
    summarise(
      ypad = max(abs(.data[[ycol]]), na.rm = TRUE) * 1.1,
      x_min = min(Day, na.rm = TRUE),
      x_max = max(Day, na.rm = TRUE),
      .groups = "drop"
    ) %>%
    transmute(Quantity, ymin = -ypad, ymax = ypad, x_min, x_max)

  ggplot(
    df,
    aes(x = Day, y = .data[[ycol]], colour = Scenario, shape = Scenario)
  ) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50") +
    geom_point(
      position = position_jitter(width = jitter_width, height = 0),
      alpha = alpha_pt,
      size = pt_size
    ) +
    geom_blank(data = pad_df, aes(x = x_min, y = ymin), inherit.aes = FALSE) +
    geom_blank(data = pad_df, aes(x = x_max, y = ymax), inherit.aes = FALSE) +
    facet_wrap(
      ~Quantity,
      nrow = 1,
      labeller = labeller(Quantity = var_labs),
      scales = "free_y"
    ) +
    scale_color_manual(
      values = c(
        NoTreatment = "#0072B2",
        PanCytoVir10mg = "#009E73",
        PanCytoVir100mg = "#D55E00"
      ),
      name = "Scenario",
      labels = scen_labs
    ) +
    scale_shape_manual(
      values = shape_vals,
      name = "Scenario",
      labels = scen_labs
    ) +
    xlab("Time (days)") +
    ylab("NLL-weighted standardized residuals") +
    theme_bw(base_size = 14) +
    theme(
      legend.position = "top",
      strip.background = element_blank(),
      strip.text = element_text(size = 12)
    )
}


nsamp <- min(1, length(bestfit_list))
# comment out the line above if you want to generate plots for all samples
# nsamp <- length(bestfit_list)

for (i in seq_len(nsamp)) {
  # get data from best fit object
  bf <- bestfit_list[[i]]
  dat <- bf$fitdata # columns: Scenario, Day, Quantity, Value, ...

  if (is.null(df_list[[i]])) {
    warning(sprintf("No dose-response time series found for sample %d; skipping.", i))
    next
  }

  # get model simulations from the dose-response object for the indicated parameter sample
  sim <- df_list[[i]] |>
    filter(Schedule == 's1', Dose %in% dose_levels) |>
    mutate(
      Scenario = factor(
        scenario_map[as.character(Dose)],
        levels = scenario_map
      )
    )
  

  # keep factor levels consistent with fitter
  dat$Scenario <- factor(
    dat$Scenario,
    levels = c("NoTreatment", "PanCytoVir10mg", "PanCytoVir100mg")
  )
  dat$Quantity <- factor(
    dat$Quantity,
    levels = c("LogVirusLoad", "IL6", "WeightLossPerc")
  )

  times_to_keep <- sort(unique(dat$Day))

  # Simulation on the observation scale used in the NLL
  sim_long <- sim %>%
    dplyr::filter(time %in% times_to_keep) %>%
    dplyr::select(time, Scenario, V, F, S) %>%
    dplyr::mutate(V = log10(pmax(1, V))) %>% # log10 with LOD clamp for virus
    dplyr::rename(
      Day = time,
      LogVirusLoad = V,
      IL6 = F,
      WeightLossPerc = S
    ) %>%
    tidyr::pivot_longer(
      cols = c(LogVirusLoad, IL6, WeightLossPerc),
      names_to = "Quantity",
      values_to = "Predicted"
    )

  # Join observed/predicted
  resid_df <- dat %>%
    dplyr::inner_join(sim_long, by = c("Scenario", "Day", "Quantity")) %>%
    dplyr::mutate(
      Residual = Value - Predicted,
      Quantity = factor(
        Quantity,
        levels = c("LogVirusLoad", "IL6", "WeightLossPerc")
      ),
      Scenario = factor(
        Scenario,
        levels = c("NoTreatment", "PanCytoVir10mg", "PanCytoVir100mg")
      )
    )

  # Rebuild sigmas from bf$fitpars + bf$fixedpars and compute pointwise variance
  sig_tbl <- gather_sigmas_tbl(bf)

  resid_df <- resid_df %>%
    dplyr::left_join(sig_tbl, by = "Quantity") %>%
    dplyr::mutate(
      Vi = pmax(add^2 + (prop * pmax(0, Predicted))^2, 1e-12)
    )

  # Per-quantity weights w_k ∝ 1/n_k, normalized to mean 1 (same as fitter)
  w_tbl <- dat %>%
    dplyr::count(Quantity, name = "n") %>%
    dplyr::mutate(w_k = (1 / n) / mean(1 / n))

  resid_df <- resid_df %>%
    dplyr::left_join(
      w_tbl %>% dplyr::select(Quantity, w_k),
      by = "Quantity"
    ) %>%
    dplyr::mutate(
      NLLWeightedResid = sqrt(w_k) * (Residual / sqrt(Vi))
    )

  # shapes per scenario (respect detected levels)
  scen_levels <- levels(resid_df$Scenario)
  shape_vals <- setNames(c(16, 17, 15)[seq_along(scen_levels)], scen_levels)

  # ---------------- (A) Combined residuals (all variables together; with jitter) ----------------
  y_max_comb <- max(abs(resid_df$NLLWeightedResid), na.rm = TRUE)
  if (!is.finite(y_max_comb) || y_max_comb == 0) {
    y_max_comb <- 1
  }
  y_pad_comb <- 0.1 * y_max_comb
  y_lim_comb <- c(-(y_max_comb + y_pad_comb), y_max_comb + y_pad_comb)

  p_combined <- ggplot(
    resid_df,
    aes(x = Day, y = NLLWeightedResid, colour = Quantity, shape = Scenario)
  ) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "grey50") +
    geom_point(
      position = position_jitter(width = jitter_width_combined, height = 0),
      alpha = alpha_combined,
      size = pt_size
    ) +
    scale_color_manual(
      values = var_colors,
      name = "Variable",
      labels = var_labs,
      guide = guide_legend(order = 1)
    ) +
    scale_shape_manual(
      values = shape_vals,
      name = "Scenario",
      labels = scen_labs,
      guide = guide_legend(order = 2)
    ) +
    scale_y_continuous(limits = y_lim_comb, expand = expansion(mult = 0)) +
    xlab("Time (days)") +
    ylab("NLL-weighted standardized residuals") +
    theme_bw(base_size = 14) +
    theme(
      legend.position = "top",
      legend.box = "vertical" # stack guides so they form two lines (variables, then scenarios)
    )

  print(p_combined)
  png(
    here::here(
      "results",
      "figures",
      paste0("residuals-nllweighted-combined", i, ".png")
    ),
    width = 8,
    height = 5,
    units = "in",
    res = 300
  )
  print(p_combined)
  dev.off()

  # ---------------- (B) Faceted residuals (per variable; with jitter) -------------------
  p_panel <- build_panel_plot(
    resid_df,
    "NLLWeightedResid",
    alpha_panel,
    shape_vals,
    jitter_width_panel
  )

  print(p_panel)
  png(
    here::here(
      "results",
      "figures",
      paste0("residuals-nllweighted-panels", i, ".png")
    ),
    width = 8.5,
    height = 5,
    units = "in",
    res = 300
  )
  print(p_panel)
  dev.off()

  # ---------------- (C) Predicted vs Observed (faceted; no jitter) --------------------
  gof_df <- resid_df %>%
    dplyr::transmute(
      Scenario,
      Quantity,
      Observed = Value,
      Predicted = Predicted
    )

  # Per-facet identical x/y ranges (with small padding)
  lims_df <- gof_df %>%
    dplyr::group_by(Quantity) %>%
    dplyr::summarise(
      low = min(c(Observed, Predicted), na.rm = TRUE),
      high = max(c(Observed, Predicted), na.rm = TRUE),
      .groups = "drop"
    ) %>%
    dplyr::mutate(
      pad = 0.05 * (high - low + ifelse(high - low == 0, 1, 0)),
      low = low - pad,
      high = high + pad
    )
  lims_pts <- dplyr::bind_rows(
    lims_df %>% dplyr::transmute(Quantity, x = low, y = low),
    lims_df %>% dplyr::transmute(Quantity, x = high, y = high)
  )

  p_gof <- ggplot(
    gof_df,
    aes(x = Observed, y = Predicted, colour = Scenario, shape = Scenario)
  ) +
    geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed",
      colour = "grey50"
    ) +
    geom_point(alpha = alpha_gof, size = pt_size) +
    geom_blank(data = lims_pts, aes(x = x, y = y), inherit.aes = FALSE) +
    facet_wrap(
      ~Quantity,
      nrow = 1,
      labeller = labeller(Quantity = var_labs),
      scales = "free"
    ) +
    theme(aspect.ratio = 1) +
    scale_color_manual(
      values = c(
        NoTreatment = "#0072B2",
        PanCytoVir10mg = "#009E73",
        PanCytoVir100mg = "#D55E00"
      ),
      name = "Scenario:",
      labels = scen_labs
    ) +
    scale_shape_manual(
      values = shape_vals,
      name = "Scenario:",
      labels = scen_labs
    ) +
    xlab("Observed") +
    ylab("Predicted") +
    theme_bw(base_size = 14) +
    theme(
      strip.background = element_blank(),
      strip.text = element_text(size = 12),
      legend.position = "top"
    )

  print(p_gof)
  png(
    here::here("results", "figures", paste0("pred-vs-obs-combined", i, ".png")),
    width = 8,
    height = 5,
    units = "in",
    res = 300
  )
  print(p_gof)
  dev.off()

  # ---------------- (D) Predicted vs Observed — single panel, all variables ----------------
  # Global limits so x & y share identical ranges across all variables
  lim_low <- min(c(gof_df$Observed, gof_df$Predicted), na.rm = TRUE)
  lim_high <- max(c(gof_df$Observed, gof_df$Predicted), na.rm = TRUE)
  pad <- 0.05 * (lim_high - lim_low + ifelse(lim_high - lim_low == 0, 1, 0))
  lim_low <- lim_low - pad
  lim_high <- lim_high + pad

  p_gof_all <- ggplot(
    gof_df,
    aes(x = Observed, y = Predicted, colour = Quantity, shape = Scenario)
  ) +
    geom_abline(
      slope = 1,
      intercept = 0,
      linetype = "dashed",
      colour = "grey50"
    ) +
    geom_point(alpha = alpha_gof_all, size = pt_size) +
    scale_color_manual(
      values = var_colors,
      name = "Variable",
      labels = var_labs,
      guide = guide_legend(order = 1)
    ) +
    scale_shape_manual(
      values = shape_vals,
      name = "Scenario",
      labels = scen_labs,
      guide = guide_legend(order = 2)
    ) +
    coord_equal(
      xlim = c(lim_low, lim_high),
      ylim = c(lim_low, lim_high),
      expand = FALSE
    ) +
    xlab("Observed") +
    ylab("Predicted") +
    theme_bw(base_size = 14) +
    theme(
      legend.position = "top",
      legend.box = "vertical" # two lines: variables (color) then scenarios (shape)
    )

  print(p_gof_all)
  png(
    here::here(
      "results",
      "figures",
      paste0("pred-vs-obs-allvars-singlepanel", i, ".png")
    ),
    width = 7.5,
    height = 6,
    units = "in",
    res = 300
  )
  print(p_gof_all)
  dev.off()
}
