##########################################
# make time-series plots (other than the best fit plot)
# these show time-series for different doses explored by the simulation runs
# these figures are shown in the supplement
##########################################
source(here::here('code/plotting-code/timeseries-plot-function.R'))

# data for the time series plots is generated by the run-dose-predictions-simulations.R script.
# it is stored in the timeseries_df component of each list element
# load simulation results
df_list = readRDS(here::here('results','output','dose-response-results.Rds'))


# keep only the 'timeseries_df' from each element
df_list <- lapply(df_list, `[[`, "timeseries_df")

# only make these figures for the baseline values of the fixed parameter set
all_ts = df_list[[1]]

# make time-series plots for Schedule s1
# this is baseline and should look like the best fit plot without the data
s1_ts <- all_ts |>
  filter(Schedule == "s1") |>
  mutate(Dose = ifelse(Dose == 1, 0, Dose))

dose_levels   <- c("1 mg/kg", "10 mg/kg", "100 mg/kg")


s1plot <- plot_timeseries(data = NULL, modelfit = s1_ts, tmax = 7, dose_levels)
plot(s1plot)
png(here::here('results', 'figures', 'timeseries-baseline.png'), width = 8, height = 5, units = 'in', res = 300)
plot(s1plot)
dev.off()

# make time-series plots for Schedule s2
s2_ts <- all_ts |> 
  filter(Schedule == "s2") |> 
  mutate(Dose = ifelse(Dose == 1, 0, Dose))
s2plot <- plot_timeseries(data = NULL, modelfit = s2_ts, tmax = 7, dose_levels)
plot(s2plot)
png(here::here('results', 'figures', 'timeseries-d2tx.png'), width = 8, height = 5, units = 'in', res = 300)
plot(s2plot)
dev.off()

# make time-series plots for Schedule s3
s3_ts <- all_ts |> 
  filter(Schedule == "s3") |> 
  mutate(Dose = ifelse(Dose == 1, 0, Dose))
s3plot <- plot_timeseries(data = NULL, modelfit = s3_ts, tmax = 7, dose_levels)
plot(s3plot)
png(here::here('results', 'figures', 'timeseries-d3tx.png'), width = 8, height = 5, units = 'in', res = 300)
plot(s3plot)
dev.off()

# make time-series plots for Schedule s4
s4_ts <- all_ts |> 
  filter(Schedule == "s4") |> 
  mutate(Dose = ifelse(Dose == 1, 0, Dose))
s4plot <- plot_timeseries(data = NULL, modelfit = s4_ts, tmax = 7, dose_levels)
plot(s4plot)
png(here::here('results', 'figures', 'timeseries-dailytx.png'), width = 8, height = 5, units = 'in', res = 300)
plot(s4plot)
dev.off()

# make time-series plots for Schedule s5
s5_ts <- all_ts |> 
  filter(Schedule == "s5") |> 
  mutate(Dose = ifelse(Dose == 1, 0, Dose))
s5plot <- plot_timeseries(data = NULL, modelfit = s5_ts, tmax = 7, dose_levels)
plot(s5plot)
png(here::here('results', 'figures', 'timeseries-singletx.png'), width = 8, height = 5, units = 'in', res = 300)
plot(s5plot)
dev.off()