##########################################
# make time-series plots (other than the best fit plot)
# these show time-series for different doses explored by the simulation runs
# these figures are shown in the supplement
##########################################
# load packages needed by this script and function
library(ggplot2)
library(dplyr)
library(patchwork)
library(here)

source(here::here('code/plotting-code/timeseries-plot-function.R'))

# data for the time series plots is generated by the run-dose-predictions-simulations.R script.
# it is stored in the timeseries_df component of each list element
# load simulation results
dose_results <- readRDS(here::here(
  'results',
  'output',
  'dose-response-results.Rds'
))

# determine the dose levels for which full time-series were recorded
timeseries_doses <- attr(dose_results, "ts_doses")
if (is.null(timeseries_doses) || !length(timeseries_doses)) {
  timeseries_doses <- dose_results[[1]]$ts_doses
}

# fall back to the unique values in the time-series data if needed
if (is.null(timeseries_doses) || !length(timeseries_doses)) {
  timeseries_doses <- dose_results[[1]]$timeseries_df$Dose
}

timeseries_doses <- sort(unique(timeseries_doses))

format_dose_label <- function(dose) {
  if (isTRUE(all.equal(dose, 0))) {
    return("no drug")
  }
  paste0(format(dose, trim = TRUE, scientific = FALSE), " mg/kg")
}

dose_levels_labels <- vapply(timeseries_doses, format_dose_label, character(1))

# keep only the 'timeseries_df' from each element
df_list <- lapply(dose_results, `[[`, "timeseries_df")

# only make these figures for the baseline values of the fixed parameter set
all_ts <- df_list[[1]]

schedule_files <- c(
  s1 = 'timeseries-baseline.png',
  s2 = 'timeseries-d2tx.png',
  s3 = 'timeseries-d3tx.png',
  s4 = 'timeseries-dailytx.png',
  s5 = 'timeseries-singletx.png'
)

for (schedule_id in names(schedule_files)) {
  schedule_df <- all_ts |>
    filter(Schedule == schedule_id)

  if (!nrow(schedule_df)) {
    warning(sprintf("No trajectories found for schedule '%s'", schedule_id))
    next
  }

  ts_plot <- plot_timeseries(
    data = NULL,
    modelfit = schedule_df,
    tmax = 7,
    dose_levels = timeseries_doses,
    dose_levels_labels = dose_levels_labels
  )

  plot(ts_plot)

  png(
    here::here('results', 'figures', schedule_files[[schedule_id]]),
    width = 8,
    height = 5,
    units = 'in',
    res = 300
  )
  plot(ts_plot)
  dev.off()
}
