##########################################
# make dose plots
##########################################

source(here::here("code", "plotting-code", "dose-response-plot-function.R"))

# load simulation results generated by run-dose-predictions-simulation.R

dose_response_list = readRDS(here::here('results','output','dose-response-results.Rds'))



# ---- Generate Figures ----
fig1 <- plot_outcomes(dose_response_list, scenarios = "baseline")
print(fig1)
filename = here("results", "figures", "dose-response-baseline.png")
ggsave(filename, fig1, width = 12, height = 4)

fig2 <- plot_outcomes(dose_response_list, scenarios = c("baseline", "d2 start", "d3 start"))
print(fig2)
filename = here("results", "figures", "dose-response-txstart.png")
ggsave(filename, fig2, width = 12, height = 4)

fig3 <- plot_outcomes(dose_response_list, scenarios = c("baseline", "daily tx", "single tx"))
print(fig3)
filename = here("results", "figures", "dose-response-txinterval.png")
ggsave(filename, fig3, width = 12, height = 4)

